#!/usr/bin/env python
import sys
import argparse

from pysimm import zcode
from treatyofbabel.wrappers import blorb
from os.path import abspath, basename, exists

try:
    from Tkinter import Tk
    from tkFileDialog import askopenfile
    from tkMessageBox import showinfo, showerror
    tk_avail = True
except:
    tk_avail = False

def print_or_msgbox(string, mode = 'error'):
    if tk_avail:
        if mode == 'error':
            showerror('zverify', string)
        else:
            showinfo('zverify', string)
    else:
        if mode == 'error':
            sys.stderr.write(''.join((string, '\n')))
        else:
            print string

parser = argparse.ArgumentParser(description = 'Verify the integrity of a \
                                                Z-code file.')

input_arg_keys = {'metavar': 'story',
                  'type': argparse.FileType('rb'),
                  'help': 'Z-code story file.',
                  'default': None}
if tk_avail:
    input_arg_keys['help'] = ' '.join((input_arg_keys['help'],
               'A file dialog will appear if this argument is not provided.'))
    input_arg_keys['nargs'] = '?'
parser.add_argument('story', **input_arg_keys)
story = parser.parse_args().story

if tk_avail:
    Tk().withdraw()

if story == None:
    if tk_avail:
        story = askopenfile(title = 'zverify', mode = 'rb',
                            filetypes = [('Z-code files',
                                          '.z1 .z2 .z3 .z4 .z5 .z6 \
                                           .z7 .z8 .zlb .zblorb .dat'),
                                         ('All files', '*')])
    else:
        pass
else:
    print_or_msgbox('No story file chosen.')
    sys.exit()

zstory = zcode.StoryFile(story)
story.close()

if zstory.verify():
    print_or_msgbox('Story file verified as intact.', 'info')
    
else:
    print_or_msgbox('Story file not verified as intact.')

sys.exit()
